name: macnewsome
favicon: null
layout_spectrum: 0.7527725005056709
typography_spectrum: 0.29593975958414376
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7196892609354109
  lightness: 0.8095116335898638
  saturation: 0.3636783950496465
  rhythmicContrast: 0.7134134811349213
purpose: []
