name: macnewsome
favicon: null
layout_spectrum: 0.54248
typography_spectrum: 0.69564
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#4f2766'
    - '#afadb2'
    - '#8f8397'
    - '#f9ba1f'
  brandStrength: 0.6875
  lightness: 0.375
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
